# -*- coding: utf-8 -*-
"""emotion_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPnPd0lRRQn4f_n7tTuhlLTS74NaTUQG
"""

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

analyzer = SentimentIntensityAnalyzer()

def detect_emotion(text):
    scores = analyzer.polarity_scores(text)
    compound = scores['compound']

    if compound >= 0.4:
        emotion = "happy"
    elif compound <= -0.4:
        emotion = "frustrated"
    else:
        emotion = "neutral"

    intensity = abs(compound)
    return emotion, intensity

