# -*- coding: utf-8 -*-
"""tts_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uK0gPDfBGLG_D9rW4DeAGz4l__nvy1AN
"""

!pip install gTTS

from gtts import gTTS

def synthesize_speech(text, filename="static/output.mp3"):
    tts = gTTS(text=text, lang="en")
    tts.save(filename)

